title: Tauseef Jamadar
description: Stuff that I come across and find interesting.
author: Tauseef Jamadar
email: tmjam.ahmed@gmail.com
phone: (650) 576-5403
github: https://github.com/tmjam
about: I am a Software Engineer at <a href="https://www.build.com" target="_blank">Build.com</a> and a freelance developer. I love working on backend and frontend technologies.
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/tjamadar"
    - icon: fa-twitter
      link: "https://twitter.com/tmjam3011"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/tmjam"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
